### ISSUE TITLE
Purchasing text messages or tweets moving screen

### ISSUE THREAD

**Issue by gbear605** [Sidetalker/TapMonkeys#11] opened 2015-05-18 01:52 UTC
When you buy a tweet or text message, the screen scrolls up a small amount, then scrolls back down. This doesn't always happen for the text message - if the screen is scrolled up enough to start with, then it won't scroll up.

**Comment by gbear605** [comment] 2015-05-18 01:55
Having unlocked Jabba the Monkey, I noticed that this also happened with him a few times, but not often.

**Comment by gbear605** [comment] 2015-05-18 02:52
And I just had this happen with Sea Monkey and Elementary School

**Comment by Sidetalker** [comment] 2015-05-18 18:54
Reminder for self - likely is due to reloadData() messing with the constraints in the cells, forcing them to readjust from the estimated cell height. May end up being best just to implement heightForRow and calculate the height of the description label manually.

**Comment by Sidetalker** [comment] 2015-05-18 21:09
@Gbear605 unable to reproduce in 0.0.4.6. Could you use the new in-app bug reporting tool to get me a screenshot + metadata when the screen is positioned in such a way that tapping the button would produce the bug?

**Comment by Sidetalker** [comment] 2015-05-19 00:51
Never mind, was able to reproduce in device

**Comment by Sidetalker** [comment] 2015-05-19 17:13
Duplicated here: https://github.com/Sidetalker/TapMonkeys/issues/17

**Comment by Sidetalker** [comment] 2015-05-19 17:44
Fixed in 0.0.4.9

**Closed as completed by Sidetalker** 2015-05-19 17:44 UTC
Labels: bug
